# Generated by Django 5.2.11 on 2026-03-03 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram')], default='kg', max_length=2)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('diagnosis', models.TextField()),
                ('treatment_protocol', models.TextField()),
                ('next_visit_date', models.DateField(blank=True, db_index=True, null=True)),
                ('doctor_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_recorded', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='owners.pet')),
            ],
        ),
    ]
