# Generated by Django 5.2.11 on 2026-02-22 06:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(help_text='Weight in Kilograms')),
                ('diagnosis', models.TextField()),
                ('treatment_protocol', models.TextField()),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='owners.pet')),
            ],
        ),
    ]
