# Generated by Django 5.2.11 on 2026-02-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram')], default='kg', max_length=2),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weight',
            field=models.FloatField(),
        ),
    ]
