# Generated by Django 5.2.11 on 2026-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_weight_unit_alter_visit_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
