# Generated by Django 5.2.11 on 2026-03-03 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='clinics.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_types', to='clinics.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('birthdate', models.DateField()),
                ('favorite_food', models.CharField(blank=True, max_length=255, null=True)),
                ('food_allergy', models.BooleanField(default=False)),
                ('food_allergy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='owners.owner')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owners.pettype')),
            ],
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['name', 'phone_number'], name='owner_name_phone_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pettype',
            unique_together={('clinic', 'name')},
        ),
    ]
