# Generated by Django 5.2.11 on 2026-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='food_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='food_allergy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
