# Generated by Django 5.2.11 on 2026-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_pet_favorite_food_pet_food_allergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['name', 'phone_number'], name='owner_name_phone_idx'),
        ),
    ]
