# Generated by Django 5.2.11 on 2026-03-03 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to='clinics.clinic')),
                ('pet_types', models.ManyToManyField(blank=True, related_name='cages', to='owners.pettype')),
            ],
            options={
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BoardingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_types', to='clinics.clinic')),
                ('cages', models.ManyToManyField(related_name='boarding_types', to='boarding.cage')),
            ],
            options={
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BoardingPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cage_name', models.CharField(blank=True, max_length=50, null=True)),
                ('boarding_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boardings_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boardings_checked_out', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardings', to='owners.pet')),
                ('boarding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boarding.boardingtype')),
                ('cage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boardings', to='boarding.cage')),
            ],
        ),
    ]
