# Generated by Django 5.2.11 on 2026-02-22 06:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cages', to='owners.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cages', models.ManyToManyField(related_name='boarding_types', to='boarding.cage')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardings', to='owners.pet')),
                ('boarding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boarding.boardingtype')),
                ('cage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boardings', to='boarding.cage')),
            ],
        ),
    ]
