# Generated by Django 5.2.11 on 2026-02-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0001_initial'),
        ('owners', '0002_pet_favorite_food_pet_food_allergy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cage',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='cage',
            name='pet_types',
            field=models.ManyToManyField(blank=True, related_name='cages', to='owners.pettype'),
        ),
    ]
