# Generated by Django 5.1.7 on 2026-02-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0002_remove_cage_pet_type_cage_pet_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingpet',
            name='boarding_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boardingpet',
            name='cage_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boardingpet',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
