# Generated by Django 5.2.11 on 2026-02-27 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0003_boardingpet_boarding_type_name_boardingpet_cage_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingpet',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boardings_checked_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardingpet',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boardings_checked_out', to=settings.AUTH_USER_MODEL),
        ),
    ]
