# Generated by Django 5.2.11 on 2026-02-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0004_boardingpet_checked_in_by_boardingpet_checked_out_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingpet',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
