# Generated by Django 5.2.11 on 2026-02-28 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0005_boardingpet_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingpet',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardingpet',
            name='start_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
