# Generated by Django 5.2.11 on 2026-03-03 03:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_infinite', models.BooleanField(default=False, help_text='If enabled, items in this category have unlimited quantity and no expiry tracking.')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, choices=[('bottles', 'Bottles'), ('vials', 'Vials'), ('mg', 'Milligrams (mg)'), ('ml', 'Milliliters (ml)'), ('boxes', 'Boxes'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('pieces', 'Pieces'), ('ampoules', 'Ampoules'), ('cans', 'Cans'), ('pouches', 'Pouches'), ('doses', 'Doses'), ('strips', 'Strips'), ('syringes', 'Syringes'), ('packs', 'Packs')], help_text='Select a unit', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='clinics.clinic')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(blank=True, help_text='e.g. supplier, lot number', max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['expiration_date', 'date_received'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Show a low-stock warning when total quantity is at or below this number.')),
                ('expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Show an expiry warning when the nearest batch expires within this many days.')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_preferences', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Inventory Preference',
                'verbose_name_plural': 'Inventory Preferences',
            },
        ),
    ]
