# Generated by Django 5.2.11 on 2026-03-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='inventory_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('petshop', 'Petshop')], default='clinic', help_text='Whether this category belongs to the clinic or petshop inventory.', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('clinic', 'name', 'inventory_type')},
        ),
    ]
