# Generated by Django 5.1.7 on 2026-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_inventory_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('bottles', 'Bottles'), ('vials', 'Vials'), ('mg', 'Milligrams (mg)'), ('ml', 'Milliliters (ml)'), ('boxes', 'Boxes'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('pieces', 'Pieces'), ('ampoules', 'Ampoules'), ('cans', 'Cans'), ('pouches', 'Pouches'), ('doses', 'Doses'), ('strips', 'Strips'), ('syringes', 'Syringes'), ('packs', 'Packs')], help_text='Select a unit', max_length=50, null=True),
        ),
    ]
